### ISSUE TITLE
Mesh-VPN wizard text links to missing wiki page

### ISSUE THREAD

**Issue by pabloaul** [freifunk-darmstadt/site-ffda#22]
After setting up my node at the Mesh-VPN key page, I found this link to wiki.darmstadt.freifunk.net which does not exist anymore.
https://github.com/freifunk-darmstadt/site-ffda/blob/f63bd77ae9c2e3fdd479761dfc8e976bada9aad8/i18n/en.po#L36

**Comment by herbetom** [comment]
I also noticed that a while ago but haven't fixed it yet ...

https://git.darmstadt.ccc.de/ffda/firmware/site/-/issues/1

If you've got a suggestion, a PR would be welcome :)

**Comment by pabloaul** [comment]
Opened an issue instead because I wouldn't know where else to point this link. Don't know if the wiki page of other communities would be a viable pick since some contain specific implementation details.
